version: '3.1'

services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
  db_test:
    image: postgres
    ports:
      - 5433:5433
    env_file:
      - .env
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - .env
    depends_on:
      - db

